# Экономный режим Gradle: песочница сборки имеет ~1.5 ГБ ОЗУ.
# Если у вас обычный компьютер/CI — закомментируйте две строки с Xmx для ускорения.
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=false
android.useAndroidX=false
android.nonTransitiveRClass=true
kotlin.daemon.jvmargs=-Xmx512m
